name: libsodium
description: dart bindings for libsodium, a modern, easy-to-use crypto library.
version: 0.2.0
homepage: https://github.com/thelmuxkriovar/libsodium-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  test: ^1.15.7