name: libsodium
description: dart bindings for libsodium, a modern, easy-to-use crypto library.
version: 0.1.11
homepage: https://github.com/thelmuxkriovar/libsodium-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  test: ^1.15.7